server:
  port: 8082
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      suffix: .txt
      directory: logs
      file-date-format: yyyy-MM-dd-HH
      pattern: '[%{yyyy-MM-dd HH:mm:ss}t] %s "%r" requested.'

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deep_card
    username: root
    hikari:
      password: rnwkgus
#      password: Qwe123!@#
  jpa:
    hibernate:
      ddl-auto: update
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2KB
#      max-file-size: 80MB
#      max-request-size: 90MB

webClient:
  servers:
    userServer:
      path: https://api.ddeep.store
#      path: http://localhost:8081
#    imageServer:
#      key: d15ee2fe18d2ebe2ef7afda51ffd3114e5cd1f29dc8fd70e3ffee96b698ceed027a0
#      path: https://api.ddeep.store
#      path: http://localhost:8083