server:
  port: 8082

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deep_card
    username: root
    hikari:
      password: rnwkgus
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 80MB
      max-request-size: 90MB

webClient:
  servers:
    userServer:
      path: http://172.20.10.3:8081
    imageServer:
      path: http://101.101.217.155:8083